name: ci/build-check

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main

jobs:
  build-check:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0
          cache: true

      - name: restore
        run: dotnet restore --use-lock-file
      
      - name: lint
        run: dotnet format --verify-no-changes --no-restore
      
      - name: test
        run: dotnet test --no-restore

      - name: build
        run: dotnet build --no-restore --no-logo -v q --property WarningLevel=0 /clp:ErrorsOnly